import localFont from 'next/font/local'
import type { Metadata } from "next";
import "./globals.css";

const raptorV2 = localFont({
  src: './fonts/Raptor V2 Premium Semibold.ttf',
  display: 'swap',
  variable: '--font-raptor',
})

const abcDiatypeLight = localFont({
  src: './fonts/ABCDiatype Light.otf',
  display: 'swap',
  variable: '--font-abcdiatype',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raptorV2.variable} ${abcDiatypeLight.variable}`}>
      <body className={abcDiatypeLight.className}>
        {children}
      </body>
    </html>
  );
}
