export const writingArticle = {
  title: 'What is the purpose of intelligence without taste?',
  deck: 'Systems can get smarter and still remain aesthetically and strategically lost.',
  datePublished: 'April 17, 2026',
  image: {
    src: '/images/semantic-openness.png',
    alt: 'Matrix comparing semantic openness and dimensionality.'
  },
  paragraphs: [
    "Enough has been written about what taste is. My aim here is to understand what taste means for the machine, and why the machine can't get further without it.",
    "Taste is a form of intelligence for navigating high-dimensional, semantically open domains. In other words, the hardest kind of taste is hard because a lot of things are at play at once, there isn't one right answer, and what works shifts with context, person, moment, and stance. Styling is one of those domains. So is interior design. So is a lot of creative work where the product is judgement itself and knowing when to break rules.",
    'At Etto, we are building tools for stylists, interior designers, and other creative industry professionals whose work lives in these kinds of domains. The following observations assess the gap between applied taste and how AI currently understands it. A diagnosis in service to how to think about building products and benchmarks for high-dimensional, semantically open creative work.',
    `Elite taste is two things: compression and orientation. Compression is the idea that we absorb all this ambiguity and collapse it into a judgement call. Orientation is opinionated: not "what do people like," but "what should be liked from where I stand?" This is the part we could call je ne sais quoi. The thing that makes the judgement feel like it came from someone cool. The person with elite taste has their own innuendo and obsessions, but they are also responding to the world around them in a unique way.`,
    "Ye is a creative genius in dialogue with himself whose work lands despite being controversial. Nadia Lee Cohen is cool because she renders character studies as high-resolution cinematic work that is so recognizable within a scene. Danielle Goldberg is a master stylist whose work is highly identifiable amongst those in the know, and it lands well because every look is addressed to her client situated in a specific scene, in a specific press cycle, all while maintaining both the client's and Danielle's signature.",
    'A talented artist friend of mine was given new work by an existing client, and the entire brief was "just make it cool." "Just make it cool" is a compressed brief. The person on the other side of that query has to internalize a large amount of context without being told it. A non-compressed version of the brief would spell out the palette, the references, the audience, the constraints, the mood, the directions. That is precisely what the brief is outsourcing. They trusted her to figure out what "cool" meant here and to make the right choices without needing everything decompressed in advance. This is what "taste" does. It absorbs ambiguity and collapses it into judgement.',
    `Search, on the other hand, does almost the opposite. You give it a query, and it expands the space into options. Taste, instead, takes a lot of context and returns an opinionated judgement without showing the work. Search and recommendation interfaces start to strain when the query is personal, high-stakes, and high-intent all at once. "What style suits me," "does this painting belong in my collection," "which pieces from this collection actually belong in my closet." These are compression queries. The answer depends on who's asking, and a list of aggregate options across many users isn't the same as a judgement call made for one person in one scene.`,
    'One rough ML analogue is the difference between reasoning and embeddings. Reasoning works best when the problem is explicit and bounded. Taste is harder because the criteria are not fully specified in advance; they are partly implicit, partly social, partly historical, and partly downstream of who is judging.',
    'A key breakthrough in modern AI was the generation of contextual embeddings. In early NLP, "bank" had the same embedding whether it was in the sentence "the river bank" or "the Bank of America." An important feature of transformers is the embeddings they produce are contextual, so "bank" gets a different embedding in not just "the river bank" and "the Bank of America," but also "the river bank was crowded" and "the river bank was serene."',
    `You can trace modern AI as a progression of learning to hold context. First, the meaning of a word depends only on the word itself. Then, on the sentence around it. Then, on the specific user asking. Personalized reward models push this idea further, as they are addressing another kind of context: a "good" thing for an LLM to say depends not only on the situation, but on the individual user in that specific situation. The state of deployed RLHF is trained on average preferences, not individual ones. Average preferences, or rather, being generic, is a fine and GOOD thing, but it is brittle. Personalized reward models are an active research direction currently built on very thin user representations (a handful of preference pairs or a paragraph-long summary injected into the prompt). And even as a direction, naive personalization optimizes for revealed user satisfaction, which is the opposite of a stylist's judgement or being disagreeable. Taste needs the model to hold a person the way a stylist might: built up slowly, situated in a scene, and carried across time. Another way to put it: current models are learning more rules. Taste is knowing when to break them.`,
    'All this explains why evaluation breaks so quickly. In semantically open spaces, the issue is not just whether an output meets constraints, but whether it expresses the right stance. Whether it feels alive. Whether it is coherent for a particular person or scene. Whether the user accepts the answer as great.'
  ],
  quote: {
    text: '“What mattered was not to give in to sensation but precisely to master it. The whole problem of taste in the eighteenth century consisted in finding an effective answer to the calls which fancy made on men, and the problem was not resolved empirically, but in terms of certain values inseparable from a concept of man and of civilization. The man of taste was an aristocrat in spirit…and the judgement of taste was aristocratic rather than democratic, for it was not founded upon the likes or dislikes of a majority.”',
    source: "from Rémy G. Saisselin's on",
    sourceTitle: 'Reflections on the Origins of Aesthetics'
  }
} as const;
